### PR TITLE
Andrey.m.drawingjava 54

### PR DESCRIPTION
**Pull request by anms23**
Aspose.Drawing Java documentation

### CODE REVIEW

**Comment by Sergey-Vlasov** [comment]
java/getting-started/installation/installation_*.png images are for .NET, not Java.

**Comment by Sergey-Vlasov** [comment]
Can you please use PNG images for screenshots, not WEBP. github preview doesn't show WEBP and other tools may not support them.

**Comment by Sergey-Vlasov** [comment]
Evaluation Version Limitations: "The number of drawing operations is limited to 100 and an exception will be thrown after that."

We have removed this limitation long time ago.

**Comment by Sergey-Vlasov** [comment]
java/getting-started/product-overview/product-overview_1 file lacks extension (it is actually PNG). Is it used?

**Comment by Sergey-Vlasov** [comment]
java/home_1.png is icon for .NET, not Java.

**Comment by Sergey-Vlasov** [comment]
java/testdata/SourceImages/*.* are these files used?

**Comment by anms23** [comment]
Fixed the issues above https://github.com/aspose-drawing/Aspose.Drawing-Documentation/pull/16/commits/1937f864df1aa5eb561bb03b23976cdb0526cc8d

**Pull request merged**
